// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "ÐÐ²Ñ‚Ð¾Ð¼Ð°Ñ‚Ð¸Ñ‡ÐµÑÐºÐ¸",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Ð’Ñ€ÑƒÑ‡Ð½ÑƒÑŽ",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual"
  },
  "My select": {
    "en": "My select",
    "de": "Mein Auswahl",
    "ru": "Ð’Ñ‹Ð±Ð¾Ñ€",
    "pt": "Meu selecionado",
    "nl": "Mijn select",
    "fr": "Mon choix",
    "it": "La mia selezione",
    "es": "Mi seleccion"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "ÐŸÑ€Ð¸ ÑÐ¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ð¸ Ð½Ð°ÑÑ‚Ñ€Ð¾ÐµÐº Ð°Ð´Ð°Ð¿Ñ‚ÐµÑ€Ð° Ð¾Ð½ ÑÑ€Ð°Ð·Ñƒ Ð¶Ðµ Ð¿ÐµÑ€ÐµÐ·Ð°Ð¿ÑƒÑÐºÐ°ÐµÑ‚ÑÑ",
    "pt": "no adaptador de salvar reinicia com nova configuraÃ§Ã£o imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redÃ©marre avec la nouvelle config immÃ©diatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuraciÃ³n de inmediato"
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel",
    "ru": "ÐŸÑ€Ð¸Ð¼ÐµÑ€",
    "pt": "configuraÃ§Ãµes do adaptador de modelo",
    "nl": "sjabloon-adapterinstellingen",
    "fr": "paramÃ¨tres de l'adaptateur de modÃ¨le",
    "it": "impostazioni dell'adattatore del modello",
    "es": "configuraciÃ³n del adaptador de plantilla"
  },
  "test1": {
    "en": "Test 1",
    "de": "Test 1",
    "ru": "Ð¢ÐµÑÑ‚ 1",
    "pt": "Teste 1",
    "nl": "Test 1",
    "fr": "Test 1",
    "it": "Test 1",
    "es": "Prueba 1"
  },
  "port": {
    "en": "Port",
    "de": "Port",
    "ru": "Port",
    "pt": "Port",
    "nl": "Port",
    "fr": "Port",
    "it": "Port",
    "es": "Port"
  },
  "host": {
    "en": "Comfoair IP:",
    "de": "Comfoair IP:",
    "ru": "Comfoair IP:",
    "pt": "Comfoair IP:",
    "nl": "Comfoair IP:",
    "fr": "Comfoair IP:",
    "it": "Comfoair IP:",
    "es": "Comfoair IP:"
  },
  "whatmode": {
    "en": "Choose your Comfoair Connection - Mode",
    "de": "Wählen Sie Ihren Comfoair-Verbindungsmodus",
    "ru": "Выберите Comfoair Connection - Режим",
    "pt": "Escolha sua conexão Comfoair - Modo",
    "nl": "Kies uw Comfoair-verbinding - Modus",
    "fr": "Choisissez votre connexion Comfoair - Mode",
    "it": "Scegli la tua connessione Comfoair - Modalità",
    "es": "Elija su conexión Comfoair - Modo"
  },
  "adapteronly": {
    "en": "Adapter only, CCEase inactive",
    "de": "Nur Adapter, CCEase inaktiv",
    "ru": "Только адаптер, CCEase неактивен",
    "pt": "Apenas adaptador, CCEase inativo",
    "nl": "Alleen adapter, CCEase inactief",
    "fr": "Adaptateur uniquement, CCEase inactif",
    "it": "Solo adattatore, CCEase inattivo",
    "es": "Solo adaptador, CCEase inactivo"
  },
  "listen": {
    "en": "Listening only",
    "de": "Abhör-Modus, keine Befehle",
    "ru": "Только прослушивание",
    "pt": "Apenas ouvindo",
    "nl": "Alleen luisteren",
    "fr": "Écoute uniquement",
    "it": "Solo ascolto",
    "es": "Solo escuchar"
  },
  "listencontrol": {
    "en": "Paralell Mode",
    "de": "Parallelbetrieb",
    "ru": "Параллельный режим",
    "pt": "Modo paralelo",
    "nl": "Paallall-modus",
    "fr": "Mode parallèle",
    "it": "Modalità parallela",
    "es": "Modo paralelo"
  },
  "logmode": {
    "en": "Paralell Mode in constant PC-Logmode",
    "de": "Parallelbetrieb im PC-Logmodus",
    "ru": "Режим Paralell в постоянном режиме PC-Log",
    "pt": "Modo Paralelo em Modo PC-Log constante",
    "nl": "Paralell-modus in constante pc-logmodus",
    "fr": "Mode Paralell en PC-Logmode constant",
    "it": "Modalità Paralell in modalità PC-Log costante",
    "es": "Modo Paralell en modo PC-Log constante"
  },
  "pollInterval": {
    "en": "Polling - Intervall (ms):",
    "de": "Polling - Intervall (ms):",
    "ru": "Опрос - Интервал (мс):",
    "pt": "Pesquisa - Intervalo (ms):",
    "nl": "Polling - Intervall (ms):",
    "fr": "Interrogation - Intervall (ms):",
    "it": "Polling - Intervall (ms):",
    "es": "Sondeo - Intervall (ms):"
  },

  "connectionserial": {
    "en": "Serial connection",
    "de": "Serielle Verbindung",
    "ru": "Последовательное соединение",
    "pt": "Conexão serial",
    "nl": "Seriële verbinding",
    "fr": "Connexion série",
    "it": "Connessione seriale",
    "es": "Conexión en serie"
  },

  "connectionip": {
    "en": " -<< connection",
    "de": "IP - Verbindung",
    "ru": "IP - соединение",
    "pt": "IP - conexão",
    "nl": "IP - verbinding",
    "fr": "IP - connexion",
    "it": "Connessione IP",
    "es": "IP - conexión"
  },

  "connectiontype": {
    "en": "Connection Type",
    "de": "Verbindungstyp",
    "ru": "Тип соединения",
    "pt": "Tipo de conexão",
    "nl": "Connectie type",
    "fr": "Type de connexion",
    "it": "Tipo di connessione",
    "es": "Tipo de conección"
  },

  "serialdevice": {
    "en": "Serial device address (i.e. /dev/ttyUSB0)",
    "de": "Serielle Geräteadresse (z.B. /dev/ttyUSB0)",
    "ru": "Последовательный адрес устройства (т.е. /dev/ttyUSB0)",
    "pt": "Endereço de dispositivo serial (ou seja, /dev/ttyUSB0)",
    "nl": "Serieel apparaatadres (d.w.z. /dev/ttyUSB0)",
    "fr": "Adresse du périphérique série (par exemple /dev/ttyUSB0)",
    "it": "Indirizzo del dispositivo seriale (es. /dev/ttyUSB0)",
    "es": "Dirección del dispositivo en serie (es decir, /dev/ttyUSB0)",
    "pl": "Adres urządzenia szeregowego (tj. /dev/ttyUSB0)",
    "zh-cn": "串行设备地址（即/dev/ttyUSB0）"
  },

  "mode": {
    "en": "comfoair connetion mode",
    "de": "Comfoair-Verbindungsmodus",
    "ru": "режим соединения comfoair",
    "pt": "modo de conexão comum",
    "nl": "comfoair connetion modus",
    "fr": "mode de connexion comfoair",
    "it": "modalità di connessione comfoair",
    "es": "modo de conexión comfoair"
  }
}
