// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "ÐÐ²Ñ‚Ð¾Ð¼Ð°Ñ‚Ð¸Ñ‡ÐµÑÐºÐ¸",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Ð’Ñ€ÑƒÑ‡Ð½ÑƒÑŽ",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual"
  },
  "My select": {
    "en": "My select",
    "de": "Mein Auswahl",
    "ru": "Ð’Ñ‹Ð±Ð¾Ñ€",
    "pt": "Meu selecionado",
    "nl": "Mijn select",
    "fr": "Mon choix",
    "it": "La mia selezione",
    "es": "Mi seleccion"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "ÐŸÑ€Ð¸ ÑÐ¾Ñ…Ñ€Ð°Ð½ÐµÐ½Ð¸Ð¸ Ð½Ð°ÑÑ‚Ñ€Ð¾ÐµÐº Ð°Ð´Ð°Ð¿Ñ‚ÐµÑ€Ð° Ð¾Ð½ ÑÑ€Ð°Ð·Ñƒ Ð¶Ðµ Ð¿ÐµÑ€ÐµÐ·Ð°Ð¿ÑƒÑÐºÐ°ÐµÑ‚ÑÑ",
    "pt": "no adaptador de salvar reinicia com nova configuraÃ§Ã£o imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redÃ©marre avec la nouvelle config immÃ©diatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuraciÃ³n de inmediato"
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel",
    "ru": "ÐŸÑ€Ð¸Ð¼ÐµÑ€",
    "pt": "configuraÃ§Ãµes do adaptador de modelo",
    "nl": "sjabloon-adapterinstellingen",
    "fr": "paramÃ¨tres de l'adaptateur de modÃ¨le",
    "it": "impostazioni dell'adattatore del modello",
    "es": "configuraciÃ³n del adaptador de plantilla"
  },
  "test1": {
    "en": "Test 1",
    "de": "Test 1",
    "ru": "Ð¢ÐµÑÑ‚ 1",
    "pt": "Teste 1",
    "nl": "Test 1",
    "fr": "Test 1",
    "it": "Test 1",
    "es": "Prueba 1"
  },
  "port": {
    "en": "Port",
    "de": "Port",
    "ru": "Port",
    "pt": "Port",
    "nl": "Port",
    "fr": "Port",
    "it": "Port",
    "es": "Port"
  },
  "host": {
    "en": "Comfoair IP:",
    "de": "Comfoair IP:",
    "ru": "Comfoair IP:",
    "pt": "Comfoair IP:",
    "nl": "Comfoair IP:",
    "fr": "Comfoair IP:",
    "it": "Comfoair IP:",
    "es": "Comfoair IP:"
  },
  "pollInterval": {
    "en": "Polling - Intervall (ms):",
    "de": "Abfrage - Intervall (ms):",
    "ru": "Abfrage - Intervall (ms):",
    "pt": "Polling - Intervall (ms):",
    "nl": "Polling - Intervall (ms):",
    "fr": "Polling - Intervall (ms):",
    "it": "Polling - Intervall (ms):",
    "es": "Polling - Intervall (ms):"
  },
  "rs232manual": {
    "en": "RS-232 Manual - Mode (see README):",
    "de": "RS-232 Manual - Mode (see README):",
    "ru": "RS-232 Manual - Mode (see README):",
    "pt": "RS-232 Manual - Mode (see README):",
    "nl": "RS-232 Manual - Mode (see README):",
    "fr": "RS-232 Manual - Mode (see README):",
    "it": "RS-232 Manual - Mode (see README):",
    "es": "RS-232 Manual - Mode (see README):"
  }


}
